version: '3.8'

services:
  db:
    image: mongo:6.0
    container_name: blackpear_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: blackpear
      MONGO_INITDB_ROOT_PASSWORD: blackpear
      MONGO_INITDB_DATABASE: blackpear
    ports:
      - "27018:27017"
    command: ["mongod", "--bind_ip_all"]
    volumes:
      - db_data:/data/db
    networks:
      - blackpear_db_network
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      timeout: 5s
      retries: 3
      start_period: 15s

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: blackpear
      ME_CONFIG_MONGODB_ADMINPASSWORD: blackpear
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - blackpear_db_network

volumes:
  db_data:

networks:
  blackpear_db_network:
    driver: bridge