version: '3.8'

networks:
  blackpear_network:
    driver: bridge

services:
  mongo:
    image: mongo:6.0
    container_name: blackpear_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: blackpear
      MONGO_INITDB_ROOT_PASSWORD: blackpear
      MONGO_INITDB_DATABASE: blackpear
    ports:
      - "27018:27017"
    networks:
      - blackpear_network
    healthcheck:
      test: ["CMD", "mongosh", "--username", "blackpear", "--password", "blackpear", "--authenticationDatabase", "admin", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: blackpear
      ME_CONFIG_MONGODB_ADMINPASSWORD: blackpear
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - blackpear_network
  backend:
    build:
      context: .
    container_name: blackpear_backend
    working_dir: /usr/src/app
    command: /bin/sh -c "npm run seed && npm run start:prod"
    environment:
      DB_USERNAME: blackpear
      DB_PASSWORD: blackpear
      DB_NAME: blackpear
      DB_HOST: mongo
      DB_PORT: 27018
      DB_LOGGING: true
      NODE_ENV: production
    ports:
      - "5050:5050"
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
    networks:
      - blackpear_network

